"use client";

import { normalizeTicker } from "@/lib/security-classification";
import type { PriceHistoryPoint } from "@/lib/types";

// Reads the static price dataset bundled into the site (public/data/prices).
// These files are generated by scripts/build-price-history.mjs (Stooq) so the
// app needs no live API call for any covered ticker.

const BASE_PATH = process.env.NEXT_PUBLIC_BASE_PATH || "";

interface BundledFile {
  ticker: string;
  closes: [string, number][];
}

export interface BundledResult {
  prices: PriceHistoryPoint[];
  covered: string[];
  missing: string[];
}

export async function loadBundledCloses(
  tickers: string[],
): Promise<BundledResult> {
  const unique = Array.from(
    new Set(tickers.map(normalizeTicker).filter(Boolean)),
  );
  const prices: PriceHistoryPoint[] = [];
  const covered: string[] = [];
  const missing: string[] = [];

  await Promise.all(
    unique.map(async (ticker) => {
      try {
        const response = await fetch(
          `${BASE_PATH}/data/prices/${encodeURIComponent(ticker)}.json`,
          { cache: "force-cache" },
        );
        if (!response.ok) {
          missing.push(ticker);
          return;
        }
        const data = (await response.json()) as BundledFile;
        for (const [date, close] of data.closes) {
          if (Number.isFinite(close)) prices.push({ ticker, date, close });
        }
        covered.push(ticker);
      } catch {
        missing.push(ticker);
      }
    }),
  );

  return { prices, covered, missing };
}

export interface DatasetIndex {
  generatedAt: string | null;
  covered: string[];
}

export async function loadDatasetIndex(): Promise<DatasetIndex | null> {
  try {
    const response = await fetch(`${BASE_PATH}/data/prices/index.json`, {
      cache: "force-cache",
    });
    if (!response.ok) return null;
    return (await response.json()) as DatasetIndex;
  } catch {
    return null;
  }
}
